//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserTopupFeature.Api
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserTopUpAppEntities : DbContext
    {
        public UserTopUpAppEntities()
            : base("name=UserTopUpAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TopUpOption> TopUpOptions { get; set; }
        public virtual DbSet<TopUpRecord> TopUpRecords { get; set; }
    }
}
